version: "3"

services:
  entanglednode0:
    container_name: entanglednode0
    image: "entangled/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-entangled.log}
    volumes:
      - ./localnet-setup/node0/entangled:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  entanglednode1:
    container_name: entanglednode1
    image: "entangled/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-entangled.log}
    volumes:
      - ./localnet-setup/node1/entangled:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  entanglednode2:
    container_name: entanglednode2
    image: "entangled/node"
    environment:
      - ID=2
      - LOG=${LOG:-entangled.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/entangled:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  entanglednode3:
    container_name: entanglednode3
    image: "entangled/node"
    environment:
      - ID=3
      - LOG=${LOG:-entangled.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/entangled:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
